### ISSUE TITLE
Failed building cysignals

### ISSUE THREAD

**Issue by shi-bai** [fplll/fpylll#96] opened 2017-08-07 16:20 UTC
Hi guys,

I have some difficulty in installing fpylll after I updated my debian to 9

The instructions goes fine until:

 pip install -r requirements.txt

Then it reports:

```
Requirement already satisfied: Cython in ./env/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Collecting pytest (from -r requirements.txt (line 2))
  Using cached pytest-3.2.0-py2.py3-none-any.whl
Collecting cysignals (from -r requirements.txt (line 3))
  Using cached cysignals-1.6.5.tar.bz2
Collecting flake8 (from -r requirements.txt (line 4))
  Using cached flake8-3.4.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./env/lib/python2.7/site-packages (from pytest->-r requirements.txt (line 2))
Collecting py>=1.4.33 (from pytest->-r requirements.txt (line 2))
  Using cached py-1.4.34-py2.py3-none-any.whl
Collecting pyflakes<1.6.0,>=1.5.0 (from flake8->-r requirements.txt (line 4))
  Using cached pyflakes-1.5.0-py2.py3-none-any.whl
Collecting enum34; python_version < "3.4" (from flake8->-r requirements.txt (line 4))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting configparser; python_version < "3.2" (from flake8->-r requirements.txt (line 4))
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8->-r requirements.txt (line 4))
  Using cached pycodestyle-2.3.1-py2.py3-none-any.whl
Collecting mccabe<0.7.0,>=0.6.0 (from flake8->-r requirements.txt (line 4))
  Using cached mccabe-0.6.1-py2.py3-none-any.whl
Building wheels for collected packages: cysignals
  Running setup.py bdist_wheel for cysignals ... error
  Complete output from command /home/shi/suite/fpylll/env/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-VQCpkl/cysignals/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp2HIBFGpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  make: 'configure' is up to date.
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /bin/mkdir -p
  checking for gawk... gawk
  checking whether make sets $(MAKE)... yes
  checking whether make supports nested variables... yes
  configure: error: source directory already configured; run "make distclean" there first
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-VQCpkl/cysignals/setup.py", line 210, in <module>
      cmdclass=dict(build=build, build_py=build_py, install=install, bdist_egg=no_egg)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/shi/suite/fpylll/env/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-VQCpkl/cysignals/setup.py", line 92, in run
      subprocess.check_call(["sh", "configure"])
    File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['sh', 'configure']' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for cysignals
  Running setup.py clean for cysignals
Failed to build cysignals
Installing collected packages: py, pytest, cysignals, pyflakes, enum34, configparser, pycodestyle, mccabe, flake8
  Running setup.py install for cysignals ... error
    Complete output from command /home/shi/suite/fpylll/env/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-VQCpkl/cysignals/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8CtKKh-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/shi/suite/fpylll/env/include/site/python2.7/cysignals:
    running install
    running build
    make: 'configure' is up to date.
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    configure: error: source directory already configured; run "make distclean" there first
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-VQCpkl/cysignals/setup.py", line 210, in <module>
        cmdclass=dict(build=build, build_py=build_py, install=install, bdist_egg=no_egg)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/shi/suite/fpylll/env/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-VQCpkl/cysignals/setup.py", line 92, in run
        subprocess.check_call(["sh", "configure"])
      File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['sh', 'configure']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/home/shi/suite/fpylll/env/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-VQCpkl/cysignals/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8CtKKh-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/shi/suite/fpylll/env/include/site/python2.7/cysignals" failed with error code 1 in /tmp/pip-build-VQCpkl/cysignals/


```

I re-started with a fresh fpylll and it reported the same. Some info of my laptop:

uname
Linux laptop 4.9.0-3-amd64 #1 SMP Debian x86_64 GNU/Linux

python --version
Python 2.7.13

Perhaps just plain stupidity on my part and there is a quick fix?

**Comment by malb** [comment] 2017-08-07 17:00
Can you try `pip install cysignals –no-cache-dir –force-reinstall`?

**Comment by shi-bai** [comment] 2017-08-08 14:03
Hi Martin,

It returns me a similar error:

(env) [~/suite/fpylll]$ pip install cysignals --no-cache-dir
--force-reinstall
Collecting cysignals
  Downloading cysignals-1.6.5.tar.bz2 (69kB)
    100% |████████████████████████████████| 71kB 47kB/s
Installing collected packages: cysignals
  Running setup.py install for cysignals ... error
    Complete output from command /home/shi/suite/fpylll/env/bin/python2 -u
-c "import setuptools,
tokenize;__file__='/tmp/pip-build-2QSsyZ/cysignals/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
/tmp/pip-YJ3r7h-record/install-record.txt
--single-version-externally-managed --compile --install-headers
/home/shi/suite/fpylll/env/include/site/python2.7/cysignals:
    running install
    running build
    make: 'configure' is up to date.
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    configure: error: source directory already configured; run "make
distclean" there first
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2QSsyZ/cysignals/setup.py", line 210, in <module>
        cmdclass=dict(build=build, build_py=build_py, install=install,
bdist_egg=no_egg)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File
"/home/shi/suite/fpylll/env/local/lib/python2.7/site-packages/setuptools/command/install.py",
line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in
run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-2QSsyZ/cysignals/setup.py", line 92, in run
        subprocess.check_call(["sh", "configure"])
      File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['sh', 'configure']' returned
non-zero exit status 1

    ----------------------------------------
Command "/home/shi/suite/fpylll/env/bin/python2 -u -c "import setuptools,
tokenize;__file__='/tmp/pip-build-2QSsyZ/cysignals/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
/tmp/pip-YJ3r7h-record/install-record.txt
--single-version-externally-managed --compile --install-headers
/home/shi/suite/fpylll/env/include/site/python2.7/cysignals" failed with
error code 1 in /tmp/pip-build-2QSsyZ/cysignals/

**Comment by malb** [comment] 2017-08-08 14:32
Did you nuke your virtualenv and tried again? The problem seems to be:

```
/home/shi/suite/fpylll/env/include/site/python2.7/cysignals:
    running install
    running build
    make: 'configure' is up to date.
    configure: error: source directory already configured; run "make
distclean" there first
```

**Comment by shi-bai** [comment] 2017-08-08 15:10
Hi,

I have deleted the fpylll and then git cloned again, then I did,

virtualenv env
source ./env/bin/activate
./install-dependencies.sh $VIRTUAL_ENV
pip install Cython
pip install pytest

and then

pip install cysignals --no-cache-dir --force-reinstall

It returns me the same error:

Collecting cysignals
  Downloading cysignals-1.6.5.tar.bz2 (69kB)
    100% |████████████████████████████████| 71kB 379kB/s
Installing collected packages: cysignals
  Running setup.py install for cysignals ... error
    Complete output from command
/home/shi/suite/fpylll/env/bin/python2 -u -c "import setuptools,
tokenize;__file__='/tmp/pip-build-rREWlG/cysignals/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install
--record /tmp/pip-RhbI0E-record/install-record.txt
--single-version-externally-managed --compile --install-headers
/home/shi/suite/fpylll/env/include/site/python2.7/cysignals:
    running install
    running build
    make: 'configure' is up to date.
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    configure: error: source directory already configured; run "make
distclean" there first
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rREWlG/cysignals/setup.py", line 210, in <module>
        cmdclass=dict(build=build, build_py=build_py, install=install,
bdist_egg=no_egg)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/shi/suite/fpylll/env/local/lib/python2.7/site-packages/setuptools/command/install.py",
line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-rREWlG/cysignals/setup.py", line 92, in run
        subprocess.check_call(["sh", "configure"])
      File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['sh', 'configure']'
returned non-zero exit status 1

    ----------------------------------------
Command "/home/shi/suite/fpylll/env/bin/python2 -u -c "import
setuptools, tokenize;__file__='/tmp/pip-build-rREWlG/cysignals/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install
--record /tmp/pip-RhbI0E-record/install-record.txt
--single-version-externally-managed --compile --install-headers
/home/shi/suite/fpylll/env/include/site/python2.7/cysignals" failed
with error code 1 in /tmp/pip-build-rREWlG/cysignals/

**Comment by malb** [comment] 2017-08-08 15:25
This is quite odd. Can you try install cysignals by hand instead of through pip. Inside your virtualenv, run `python setup.py install` for https://github.com/sagemath/cysignals

**Comment by shi-bai** [comment] 2017-08-08 16:21
Thanks Martin. It works now by manual installation.

The cysignals does not seem to support egg.

error: The package cysignals will not function correctly when built as egg.
Therefore, it cannot be installed using 'python setup.py install' or
'easy_install'. Instead, use 'pip install' to install cysignals.

I tried to clone cysignals and then
make configure
./configure  --prefix=/home/shi/suite/fpylll/env
make
make install

I don't know what happened for the pip install though ...

Cheers,
Shi

**Comment by malb** [comment] 2017-08-08 16:43
So how did you make it work in the end? I can't quite tell from your message? Also, can we close the issue?

**Comment by shi-bai** [comment] 2017-08-09 05:52
Using "pip install cysignals" does not work. But I don't know what's the
reason for that. I don't know the internals for "pip install"

I manuay installed  cysignals by using the following method:

clone cysignals to local and then (inside the virtualenv) install cysignals
to the virtualenv folder env

make configure
./configure  --prefix=/home/shi/suite/fpylll/env
make
make install

This installs cysignals into env/lib/python2.7/site-packages

After this, the rest of the installation works as usual. If no one else has
seen this problem, the issue can be closed.

**Comment by malb** [comment] 2017-08-09 09:10
Thanks for the clarification, let's keep the issue open for a few weeks to see/collect if other people are hitting it to. If not, we can close it.

**Comment by shi-bai** [comment] 2017-08-14 21:09
Martin, I have the same problem on another machine running debian 9.

Linux dain 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux

But even with "pip install cysignals" not in the virtual env, I have the same error. Surely it is an error not within fpylll; but relevant to cysignals.

**Comment by malb** [comment] 2017-08-15 09:17
Hi Shi, can you open a ticket for cysignals then? We can then try to figure this out over there.

**Comment by jdemeyer** [comment] 2017-09-08 15:02
This was reported at https://github.com/sagemath/cysignals/issues/61 so this can be closed.

It seems like a specific issue with that system that we have not been able to reproduce.

**Closed** 2017-09-08 17:01 UTC

**Comment by cryoff** [comment] 2018-02-22 15:46
If someone still has issues with installation via pip, updating existing Cython installation might help:
`sudo pip install --upgrade Cython`
