### ISSUE TITLE
An issue on BKZ 2.0

### ISSUE THREAD

**Issue by yuyang-Tsinghua** [fplll/fpylll#34] opened 2016-09-01 11:23 UTC
If I set the BKZ parameter "min_success_probability" to 0.95 rather than 0.5, then the running time of BKZ2 with blocksize = 6 on a 140-dimensional lattice would increase too much. It is strange that the performance of BKZ 2.0 is even worse than that of pure BKZ without abortion and pruning. Could you please check whether there is something wrong? Thanks.

**Comment by malb** [comment] 2016-09-01 11:36
I'm having trouble reproducing this:

```python
from fpylll import *
from copy import copy
A = IntegerMatrix.random(140, "qary", bits=40, k=70)
```

The following takes 14.8 seconds on my machine:

```python
BKZ2(copy(A))(BKZ.Param(block_size=6, min_success_probability=0.5, flags=BKZ.VERBOSE|BKZ.AUTO_ABORT))
```

The following takes 16 seconds on my machine:

```python
BKZ2(copy(A))(BKZ.Param(block_size=6, min_success_probability=0.95, flags=BKZ.VERBOSE|BKZ.AUTO_ABORT))
```

**Comment by yuyang-Tsinghua** [comment] 2016-09-01 12:26
The lattice I used is SVP challenge lattice. Please try it.

I introduce a new variable tours to control the tour number.

This is the modifications in bkz.py
`def __call__(self, params, min_row=0, max_row=-1, tours = 1): `
```
        i = 0
        while i < tours:
            with stats.context("tour"):
                clean = self.tour(params, min_row, max_row, stats)
            i += 1
            if clean or params.block_size >= self.A.nrows:
                break
            if (params.flags & BKZ.AUTO_ABORT) and auto_abort.test_abort():
                break
            if (params.flags & BKZ.MAX_LOOPS) and i >= params.max_loops:
                break
            if (params.flags & BKZ.MAX_TIME) and time.clock() - cputime_start >= params.max_time:
                break
```
This is my running code, the tours is very large, but it should be terminated in the middle.
```
beta = 6
		param =  fplll_bkz.Param(block_size=beta, min_success_probability = 0.95, strategies="default.json")
		X = ((n**2)*8)/beta**2
		BKZ2(B)(params = param, tours = X)
```

**Comment by malb** [comment] 2016-09-01 13:18
Hi, please provide a complete and minimal example of where and how it fails a la 

- "download this file" and 
- "run this code".  

Also, we cannot debug any problems in code that you have modified, please test with vanilla upstream fpylll. Indeed, your patch is unnecessary (cf. `param.max_loops`)

**Comment by yuyang-Tsinghua** [comment] 2016-09-01 14:15
HI Martin,

The lattice file is attached. The following is my code, please check.

[lat.tar.gz](https://github.com/fplll/fpylll/files/449875/lat.tar.gz)

'''
import time
from math import ceil,sqrt,log,exp

import argparse
from random import uniform,randint
import sys
import numpy as np
from copy import copy

from fpylll import IntegerMatrix
from fpylll.algorithms.simple_bkz import BKZReduction as SimpleBKZ
from fpylll.algorithms.simple_dbkz import DBKZReduction as SimpleDualBKZ
from fpylll.algorithms.bkz import BKZReduction as BKZ
from fpylll.algorithms.bkz2 import BKZReduction as BKZ2
from fpylll import BKZ as fplll_bkz
from fpylll.util import set_random_seed
           
B = IntegerMatrix.from_file('lat')
n = 140
beta = 6
param =  fplll_bkz.Param(block_size=beta, min_success_probability = 0.95, strategies="default.json")
BKZ2(copy(B))(params = param)
'''

**Comment by malb** [comment] 2016-09-01 14:41
Here's a minimal example

```python
from copy import copy
from fpylll import *
from fpylll.algorithms.bkz2 import BKZReduction as BKZ2
B = IntegerMatrix.from_file('/tmp/lat')
beta = 6
strategies = load_strategies_json(BKZ.DEFAULT_STRATEGY)
param =  BKZ.Param(block_size=beta,
                   min_success_probability = 0.95,
                   strategies=strategies, flags=BKZ.AUTO_ABORT|BKZ.VERBOSE)
BKZ2(copy(B))(params = param)
```

Running this output gives:

```
{"i": 147,  "total":    157.89,  "time":     1.07,  "preproc":     1.03,  "svp":     0.01,  "lll":     0.97,  "postproc":     0.00,  "r_0": 6.6963e+07,  "slope": -0.0620,  "enum nodes": 11.27,  "max(kappa)":  14}
```

as the last line. Running

```python
from fpylll.algorithms.bkz import BKZReduction as BKZ1
BKZ1(copy(B))(param)
```

gives

```
{"i":  61,  "total":      5.65,  "time":     0.05,  "preproc":     0.05,  "svp":     0.00,  "lll":     0.04,  "postproc":     0.00,  "r_0": 8.3886e+07,  "slope": -0.0661,  "enum nodes": 10.73,  "max(kappa)": 137}
```

as last line of output and is indeed faster.

The problem is because

```python
print strategies[6]
```

which returns

```
Strategy<  6, (), 0.50-0.50>
```

That is, with success probability 0.95 BKZ2 has to rerandomise, i.e. run LLL twice. In this block size, this is way more expensive than enumeration. Hence, the long running time. In addition, it seems rerandomisation screws with detecting BKZ reducedness of our basis, i.e. we're running more tours (and get a better reduction)

**Comment by malb** [comment] 2016-09-01 14:43
I'd say this is not a bug, but the behaviour of the underlying algorithm. Hence, I propose resolution "wontfix". Producing strategies with high target probability might be a way of alleviating the problem.

**Comment by yuyang-Tsinghua** [comment] 2016-09-01 15:14
Thanks for your reply, :-)

**Closed** 2016-09-11 14:10 UTC
