### ISSUE TITLE
PyPI package broken

### ISSUE THREAD

**Issue by cbouilla** [fplll/fpylll#163] opened 2020-02-15 05:53 UTC
Hi everyone,

This is just to inform you that the PyPI fpylll package does not install successfully.

More specifically `pip install fpylll` fails.

The problem is that the dependencies (cython, cysignals) are not marked as such in `setup.py` and therefore pip does not pull them first. But once this is solved "by hand", the build still fails because a) the fplll dev headers are not present. Fixed (under debian) with `apt install fplll-dev`. But then it still fails with b) the version of the fplll library I have on my system is not compatible... (the headers are not exactly in the same locations...)

**Comment by malb** [comment] 2020-02-15 06:20
I could never get the dependencies of `cython` and `cysignals` to work with `distutils` but maybe it now should just work™ with Python 3? I have no solution for the FPLLL issue, though.

**Comment by narendrakpatel** [comment] 2020-02-18 15:15
@malb I tried to install fpylll using `pip install fpylll` but it is failing. The problem is the same as mentioned in the previous comment by @cbouilla. 

I am currently using python version 3.8.1. It seems the problem persists in python3.

**Comment by malb** [comment] 2020-11-20 14:10
Addressed in #192

**Closed by malb** 2020-11-20 14:10 UTC
