### ISSUE TITLE
Error compiling Cython file: Constructing Python tuple not allowed without gil

### ISSUE THREAD

**Issue by yurivict** [fplll/fpylll#128] opened 2018-12-08 08:36 UTC
A lot of errors like the one below. FreeBSD 11.2. Python-3.6.

```
Error compiling Cython file:
------------------------------------------------------------
...

    if B._type != ZT_MPZ:
        raise NotImplementedError("C++ BKZ is not implemented over longs, try the Python version.")

    with nogil:
        sig_on()
             ^
------------------------------------------------------------

src/fpylll/fplll/bkz.pyx:1131:14: Constructing Python tuple not allowed without gil
```

**Comment by malb** [comment] 2018-12-08 14:48
Strange, I cannot reproduce it on Linux with Python 3.6. Does FreeBSD apply some hardening or so? I can see why it would complain but if I can't reproduce it, I'm afraid I wouldn't catch all of the instances that would need fixing.

**Comment by yurivict** [comment] 2018-12-08 17:19
I am not sure if there's something special in the commands, but here are the commands:
configure:
```
===>  Configuring for py36-fpylll-0.4.1.d.25
(cd /usr/ports/math/py-fpylll/work-py36/fpylll-0.4.1dev-25-g97b1707; /usr/bin/env XDG_DATA_HOME=/usr/ports/math/py-fpylll/work-py36  XDG_CONFIG_HOME=/usr/ports/math/py-fpylll/work-py36  HOME=/usr/ports/math/py-fpylll/work-py36 PATH=/usr/ports/math/py-fpylll/work-py36/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES LDSHARED="cc -shared" PYTHONDONTWRITEBYTECODE= PYTHONOPTIMIZE= PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer"  LDFLAGS=" -fstack-protector " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer  "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" /usr/local/bin/python3.6 -c  "import sys; import setuptools;  __file__='setup.py'; sys.argv[0]='setup.py';  exec(compile(open(__file__, 'rb').read().replace(b'\\r\\n', b'\\n'), __file__, 'exec'))" config )
/usr/local/lib/python3.6/site-packages/setuptools/dist.py:470: UserWarning: Normalizing '0.4.1dev' to '0.4.1.dev0'
  normalized_version,
running config
```

build:
```
===>  Building for py36-fpylll-0.4.1.d.25
(cd /usr/ports/math/py-fpylll/work-py36/fpylll-0.4.1dev-25-g97b1707; /usr/bin/env XDG_DATA_HOME=/usr/ports/math/py-fpylll/work-py36  XDG_CONFIG_HOME=/usr/ports/math/py-fpylll/work-py36  HOME=/usr/ports/math/py-fpylll/work-py36 PATH=/usr/ports/math/py-fpylll/work-py36/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES LDSHARED="cc -shared" PYTHONDONTWRITEBYTECODE= PYTHONOPTIMIZE= PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer"  LDFLAGS=" -fstack-protector " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer  "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" /usr/local/bin/python3.6 -c  "import sys; import setuptools;  __file__='setup.py'; sys.argv[0]='setup.py';  exec(compile(open(__file__, 'rb').read().replace(b'\\r\\n', b'\\n'), __file__, 'exec'))" build )
/usr/local/lib/python3.6/site-packages/setuptools/dist.py:470: UserWarning: Normalizing '0.4.1dev' to '0.4.1.dev0'
  normalized_version,
running build
running build_py
```

**Comment by malb** [comment] 2018-12-10 10:05
Can you try to update cysignals? It seems the version you're having somehow tries to construct a Python tuple in sig_on (?)

**Comment by jdemeyer** [comment] 2019-01-15 10:14
Please post the **complete** output from the failed build.

**Comment by jdemeyer** [comment] 2019-01-15 10:15
Also mention which Cython version you are using.

**Comment by malb** [comment] 2019-03-22 15:37
Closing since no reply. Feel free to reopen.

**Closed by malb** 2019-03-22 15:37 UTC

**Comment by Mumuuuu** [comment] 2022-12-27 01:58
OS : `Ubuntu 18.04.6 LTS on WSL`
```
Cython==0.29.32
setuptools==65.6.3
pip 22.3.1 from /home/mumu/.local/lib/python3.8/site-packages/pip (python 3.8)
```

Also same error
OS : `Ubuntu 18.04`
```
Cython==0.29.32
setuptools==65.6.3
pip 21.3.1 from /home/mumu/.local/lib/python3.8/site-packages/pip (python 3.8)
```

When I compile the SageMath source, it returns `pkg_resources.DistributionNotFound: The 'fpylll<=0.5.7,>-0.5.6' distribution was not found and is required by sagemath-standard`.
Command `python3.8 -m pip install fpylll` but got lots of error about sig_off().
[[Full Error output]](https://pastebin.com/mEJNxdzd)
